apiVersion: v1
kind: Service
metadata:
  name: movie-db-cluster-ip
spec:
  type: LoadBalancer
  selector:
    app: evergreen-admin-ui
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps: evergreen-admin-ui
  name: evergreen-admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evergreen-admin-ui
      component: frontend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: evergreen-admin-ui
        component: frontend
    spec:
      containers:
      - name: evergreen-admin-ui
        env:
          - name: VITE_API_URL
            value: http://api-evergreen.sagudeloo.com:5000
          - name: VITE_LOGIN_APP
            value: http://evergreen.sagudeloo.com/login
        image: "sagudeloo/evergreen-admin-ui:0.0.1"
        imagePullPolicy: Always
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
